nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://achilles-pinguin.ddev.site:8443/']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: false