security:
    providers:
        ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
                default_roles: ROLE_USER
                uid_key: '%env(LDAP_UID_KEY)%'

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            custom_authenticators:
                - App\Security\LdapApiAuthenticator

    access_control:
        - { path: ^/api/login,      roles: PUBLIC_ACCESS }
        - { path: ^/api/bestellung, roles: ROLE_USER }
        - { path: ^/api,            roles: ROLE_USER }
        - { path: ^/dashboard,      roles: ROLE_USER }
        - { path: ^/search,         roles: ROLE_USER }
        - { path: ^/result,         roles: ROLE_USER }
