controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login
    methods: [POST]

# ⬇️ SPA nur für GET und alles außer /api …
spa_catch_all:
    path: /{vueRouting}
    controller: App\Controller\SpaController::index
    requirements:
        vueRouting: (?!api($|/)).*   # <- /api ausschließen
    methods: [GET]                 # <- nur GET erlauben
